---
abstract: "Interface to Amazon's Route 53"
author:
  - 'Marco Fontani'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-Route53
requires:
  Digest::HMAC_SHA1: 0
  FindBin: 0
  Getopt::Long: 0
  HTML::Entities: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Mouse: 0
  Pod::Usage: 0
  XML::Bare: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/mfontani/Net-Amazon-Route53/issues
  repository: git://github.com/mfontani/Net-Amazon-Route53.git
version: 0.123250
